### PR TITLE
Feat/husky

### LINKED ISSUE #88: Feat(DevOps): Husky Set Up in monorepo
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

Currently there is no pre commit husky set up 

---

## **Describe the solution you'd like**

1. Make sure husky config is set up 
2. Run eslint pre commit
3. Run prettier pre commit 

---

## **Describe alternatives you've considered**

---

### **Additional context**

If there is any more pre commits , pre push or any other hooks . Do discuss on this issue

### PR DESCRIPTION
**Pull request by arrytiwari**
Fixes #88
features:Devops(husky setup)
Note: There are some eslint errors during the testing which @swarajbachu  is going to solve for which he has raised the issue.

### CODE REVIEW

**Comment by swarajbachu** [comment]
merge it after #94

**Comment by swarajbachu** [comment]
@dipanshuhappy was dist not included in .gitignore?

**Comment by dipanshuhappy** [comment]
> @dipanshuhappy was dist not included in .gitignore?

i did, let me confirm again

**Comment by swarajbachu** [comment]
lemme add few more things here berfore merge @dipanshuhappy

**Review by swarajbachu — APPROVED** [review]
yeah, we finally fixed a lot of build errors and eslint errors, thanks to @dipanshuhappy's contributions

**Pull request merged**
